services:
  probe_compensation:
    build:
      context: ./microservices
      dockerfile: probe_compensation/Dockerfile
    init: true
    ports:
      - "8080"
    networks:
      - metrology_net
    environment:
      - EVENT_GRID_ENDPOINT=${EVENT_GRID_ENDPOINT}
      - STORAGE_ACCOUNT_URL=${STORAGE_ACCOUNT_URL}
      - TOPIC_NAME=feature-scanned
      - SUBSCRIPTION_NAME=probe-compensation-sub
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - PYTHONUNBUFFERED=1

  alignment:
    build:
      context: ./microservices
      dockerfile: alignment/Dockerfile
    init: true
    ports:
      - "8080"
    networks:
      - metrology_net
    environment:
      - EVENT_GRID_ENDPOINT=${EVENT_GRID_ENDPOINT}
      - STORAGE_ACCOUNT_URL=${STORAGE_ACCOUNT_URL}
      - TOPIC_NAME=feature-compensated
      - SUBSCRIPTION_NAME=alignment-sub
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - PYTHONUNBUFFERED=1

  gdt_evaluation:
    build:
      context: ./microservices
      dockerfile: gdt_evaluation/Dockerfile
    init: true
    ports:
      - "8080"
    networks:
      - metrology_net
    environment:
      - EVENT_GRID_ENDPOINT=${EVENT_GRID_ENDPOINT}
      - STORAGE_ACCOUNT_URL=${STORAGE_ACCOUNT_URL}
      - TOPIC_NAME=feature-aligned
      - SUBSCRIPTION_NAME=gdt-evaluation-sub
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - PYTHONUNBUFFERED=1

  reporting:
    build:
      context: ./microservices
      dockerfile: reporting/Dockerfile
    init: true
    ports:
      - "8080"
    networks:
      - metrology_net
    environment:
      - EVENT_GRID_ENDPOINT=${EVENT_GRID_ENDPOINT}
      - STORAGE_ACCOUNT_URL=${STORAGE_ACCOUNT_URL}
      - TOPIC_NAME=feature-evaluated
      - SUBSCRIPTION_NAME=reporting-sub
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - PYTHONUNBUFFERED=1

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    networks:
      - metrology_net
    volumes:
      - ./simulation:/app/simulation
    command: streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - PYTHONPATH=/app
      - STORAGE_ACCOUNT_URL=${STORAGE_ACCOUNT_URL}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}

networks:
  metrology_net:
    driver: bridge
